config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :games do
      collection do
        post '/query', to: 'games#query', as: 'query'
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  get '/unauthorized', to: 'users#unauthorized', as: 'unauthorized'

  root "users#index"
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :system, presence: true
  validates :year, presence: true
  validates :condition, inclusion: { in: 1..3 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games

  has_secure_password

  validates :username, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
require 'http'
require 'json'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def owner?
    current_user == @user
  end

  def authorize
    @user = User.find(params[:user_id])
    redirect_to unauthorized_path unless owner?
  end

  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter 'authorize', :only => [:new, :create, :edit, :update, :delete]

  def index
  end

  def show
    find_user_game
  end

  def new
  end

  def create
    @user = User.find(params[:user_id])
    game = Game.new(game_params)
    if game.save && owner?
      redirect_to user_path(@user)
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def query
    @game_info = game_info_query(params[:game][:title])
  end

  private

  def find_user_game
    @user = User.find(params[:user_id])
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:title, :system, :year, :value, :user_id)
  end

  def game_info_query(title)
    p_title = title.gsub(/\s/, '+')
    auth_token = "b98a18fd77634c27e96a5a697b00debc6b8fd4e6"
    JSON.parse(HTTP.get("http://ae.pricecharting.com/api/product?t=#{auth_token}&q=#{p_title}"))
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      @errors = ["Username and/or password is incorrect!"]
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter 'authorize', :only => [:edit, :delete]

  def index
    @users = User.all
  end

  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      @errors = user.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def unauthorized
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def owner?
    current_user == @user
  end
end

app/helpers/games_helper.rb
module GamesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    session[:user_id] != nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_gameform.html.erb
<%= form_for :game, url: user_games_path do |f| %>

  Title:  <%= f.text_field :title %>
  System: <%= f.text_field :system %>
  Year:   <%= f.number_field :year %>
  Value:  <%= f.number_field :value %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Submit" %>

<% end %>

app/views/games/_searchform.html.erb
<%= form_for :game, url: query_user_games_path do |f| %>
  Search by Title: <%= f.text_field :title %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Submit" %>
<% end %>

app/views/games/new.html.erb
<h2>Add New Game</h2>
<%= render '/errors' %>

<h4>Enter Game Info Manually</h4>
<%= render 'gameform' %>

<h4>OR</h4>
<h4>Search PriceCharting.com for Game Info</h4>
<%= render 'searchform' %>

app/views/games/query.html.erb
<% if @game_info["status"] == "error" %>
  <h1><%= @game_info["error_message"] %></h1>
<% else %>
  <h1><%= @game_info["product-name"] %></h1>
  <p>System: <%= @game_info["console-name"] %></p>
  <p>Loose Price: <%= @game_info["loose-price"] %></p>
<% end %>

app/views/games/show.html.erb
<h2><%= @game.title %></h2>
<p><%= @game.system %> <%= @game.year %></p>
<p>Current Value: <%= @game.value %></p>

app/views/layouts/_header.html.erb
<div id="title-header">
  <h2><%= link_to("Welcome to RetroCollektor!", root_path) %></h2>
  <% if logged_in? %>
    <p> Welcome, <%= current_user.username %>! <%=link_to("Logout", session_path(current_user), method: :delete) %></p>
  <% else %>
    <%= link_to("Login", new_session_path) %>
    <%= link_to("New user? Click here to sign up!", new_user_path)%>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RetroCollektor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <%= render "layouts/header" %>
</header>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for :user, url: '/users' do |f| %>

  Username: <%= f.text_field :username %>
  Password: <%= f.password_field :password %>
  <%= f.submit "Submit", :class => 'form-button' %>

<% end %>

app/views/users/_userform.html.erb
<%= form_for :user, url: '/users' do |f| %>

  Username: <%= f.text_field :username %>
  Password: <%= f.password_field :password %>
  <%= f.submit "Submit", :class => 'form-button' %>

<% end %>

app/views/users/index.html.erb
<h1>Browse Users</h1>
<div>
  <% @users.each do |user| %>
    <h2><%= link_to(user.username, user_path(user)) %></h2>
      <p> ------------------------- </p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up!</h1>
<%= render '/errors' %>
<%= render 'userform' %>

app/views/users/show.html.erb
<div>
  <h2><%= owner? ? "Your" : "#{@user.username}'s" %> Games</h2>
  <% if owner? %>
    <%= link_to("Add new game", new_user_game_path(@user)) %>
    <% end %>

  <% @user.games.each do |game| %>
    <h4><%= link_to(game.title, user_game_path(@user, game))%> (<%= game.system %>)</h4>
  <% end %>
</div>

app/views/users/unauthorized.html.erb
<h1>You are unauthorized to access this page.</h1>

<%= link_to("home", root_path) %>